sociio_ichor/ichor/home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    
    path('donate/', views.BloodListView.as_view(), name='donate'),
    path('search-blood/', views.BloodSearchView.as_view(), name='search-blood'),
    path('donate/detail/<slug:name_slug>/', views.detail_view , name='details'),
    # path('draft/<slug:name_slug>/', views.detailDraft_view , name='draft'),
    path('about/', views.about, name='about'),
    path('contactus/', views.contactus, name = 'contact'),
    path('', views.landing, name='land'),
    path('policy/', views.privacy, name='privacy'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('donor/', views.donor_form, name='donor'),
    path('donor/confirm', views.donor_confirm, name='donor_confirm'),
    path('reviews/', views.donor_review, name='donor_review'),

]

sociio_ichor/ichor/home/models.py
from django.db import models
from django.db.models.aggregates import Max
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.db.models.signals import post_delete
from django.dispatch import receiver
from home.dj_city import cities

STATUS_DRAFT = 0
STATUS_PUBLISH = 1

STATUS = (
    (STATUS_DRAFT, "Draft"),
    (STATUS_PUBLISH, "Publish")
)
def upload_review_photo(instance, filename, *kwargs):
    file_path = 'full_name/{filename}'.format(full_name=str(instance.full_name), filename=filename)
    return file_path


BG_CHOICES = (
    ('A+','A+'),
    ('B+','B+'),
    ('O+','O+'),
    ('AB+', 'AB+'),
    ('A-','A-'),
    ('B-','B-'),
    ('O-','O-'),
    ('AB-', 'AB-'),
    ('Hh', 'Hh'),
)
TYPE=(
    ('Whole Blood', 'Whole Blood'),
    ('Plasma', 'Plasma'),
    ('Platelets', 'Platelets'),
)

class states(models.Model):
    id = models.IntegerField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255, null=False)
    def __str__(self):
        return self.name



class cities(models.Model):
    city_id = models.IntegerField(max_length=11, primary_key=True)
    city_name = models.CharField(max_length=100, null=False, default='')
    city_state = models.CharField(max_length=100, null=False, default='')

    def __str__(self):
        return self.city_name


#STATUS=(
    #('0', 'Draft'),
    #('1', 'Publish')
#)

# Create your models here.
class BloodRequest(models.Model):
    blood_request_id = models.AutoField(primary_key=True)
    time_stamp = models.DateTimeField(auto_now_add=True)
    blood_group = models.CharField(
        max_length=20, choices=BG_CHOICES, default=None, blank=True, null=True
    )
    blood_type = models.CharField(
        max_length=50, choices=TYPE, default=None, blank=True, null=True
    )
    acceptable_blood_group = models.CharField(max_length = 100, blank=True, null=True )
    Phone = models.CharField(max_length=10, default='')
    units = models.CharField(max_length=5)
    note = models.TextField(default='', blank=True, null=True)
    address = models.TextField(default='', blank=True, null=True)
    hospital_initials = models.CharField(default='', blank=False, null=False, max_length=50 )
    status = models.IntegerField(choices=STATUS, default=0)
    urgent = models.BooleanField( blank=True, default=False)
    slug = models.SlugField(max_length=400, unique=True, default=None)
    custom_field_key = models.CharField(default='', blank=True, max_length=255)
    custom_field_value = models.CharField(default='', blank=True, max_length=255)

    class Meta:
        verbose_name = 'Blood Request'
    
    
def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.name)
  
pre_save.connect(pre_save_blog_post_receiver, sender=BloodRequest)


class DonorRequest(models.Model):
    full_name = models.CharField(max_length=200, default='')
    date_of_birth = models.DateField(default=None, blank=False)
    email_id = models.EmailField(max_length=200)
    phone = models.CharField(max_length=11, default='')
    city = models.ForeignKey(cities, null=False, max_length=255, on_delete=models.CASCADE )
    state = models.ForeignKey(states, null=False, max_length=255, on_delete=models.CASCADE)

    pin_code = models.IntegerField(default=False)
    # weight = models.CharField(max_length=10, default='')
    I_agree_to_the_terms_and_conditions_stated_below = models.BooleanField(blank=False,  default=True)
    blood_group = models.CharField(
        max_length=4, choices=BG_CHOICES, default=None
    
    )    
    comment = models.TextField(default='', null=True, blank=True)
    designation = models.TextField(default='', null=True, blank=True)
    photo = models.ImageField(upload_to=upload_review_photo, blank=True, default=None, null=True)

sociio_ichor/ichor/home/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import ModelForm
from home.models import DonorRequest
from django.forms.fields import DateField
from django.contrib.admin.widgets import AdminDateWidget
# from localflavor.in.forms import INStateSelect




class ContactForm(forms.Form):
    name = forms.CharField(max_length = 150)
    company =forms.CharField(max_length=200)
    email_address = forms.EmailField(max_length = 150)
    phone = forms.CharField(max_length=10)
    message = forms.CharField(widget = forms.Textarea, max_length = 2000)

        
         
class DonorForm(forms.ModelForm):
    
    class Meta:
        model = DonorRequest
        fields = ['full_name', 'email_id', 'date_of_birth', 'phone','state', 'city', 'pin_code', 'blood_group','I_agree_to_the_terms_and_conditions_stated_below']
        widgets = {
            'full_name': forms.TextInput(attrs = {'class':'form-control'}),
            #'city': INStateSelect(attrs=None),
            #'state': forms.TextInput(attrs = {'class':'form-control'}),
            'pin_code': forms.NumberInput(attrs = {'class':'form-control'}),
            'phone': forms.TextInput(attrs = {'class':'form-control'}),
            'date_of_birth':forms.DateInput(format = '%Y-%m-%d', attrs={'type': 'date'}),
            'email_id': forms.EmailInput(attrs = {'class':'form-control'}),
            #'weight': forms.NumberInput(attrs = {'class':'form-control', 'placeholder':'Body weight'}),
        }
        
        
        
    

sociio_ichor/ichor/home/views.py
from re import template
import re
from django.db.models import query
from django.db.models.query import RawQuerySet
from django.shortcuts import render, redirect
from .models import BloodRequest, DonorRequest, STATUS_DRAFT
from django.views.generic import ListView, DetailView
from django.views import generic
from django.shortcuts import render,get_object_or_404
from .forms import ContactForm
from django.template import RequestContext


from django.core.mail import send_mail, BadHeaderError
from .models import STATUS_PUBLISH, STATUS_DRAFT
from home.forms import DonorForm
from django.db.models import Q
from django.http import HttpResponse


# Create your views here.

class BloodListView(ListView):
    model=BloodRequest
    template_name = 'home/home.html'
    queryset=BloodRequest.objects.filter(status=STATUS_PUBLISH).order_by('-time_stamp')
    context_object_name='blood'
     

class BloodSearchView(ListView):
    model=BloodRequest
    template_name='home/home.html'
    context_object_name='blood'
    
    def get_queryset(self):
        query=self.request.GET.get('q')
        return BloodRequest.objects.filter(blood_group__icontains=query, status=STATUS_PUBLISH)
    

class BloodDetailView(DetailView):
    model = BloodRequest
    template_name = 'home/home.html'
    
    
def detail_view(request, name_slug):
    blood = get_object_or_404(BloodRequest.objects.filter(status=STATUS_PUBLISH), slug=name_slug)
    return render(request, 'home/detail.html', {'blood':blood,})
    
    
def about(request):
    return render(request, 'home/about.html')



def landing(request):
    return render(request, 'home/land.html')

def privacy(request):
    return render(request, 'home/privacy.html')



def contactus(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Subject Inquiry"
            body = {
                'name': form.cleaned_data['name'], 
			    'company': form.cleaned_data['company'], 
			    'email': form.cleaned_data['email_address'], 
			    'message':form.cleaned_data['message'], 
			    'phone':form.cleaned_data['phone'], 
       
                }
            message = "\n".join(body.values())
            recepient = str(form['email_address'].value())

            try:
                send_mail(subject, message, recepient, ['sociio.organisation@gmail.com']) 
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect ("home:donate")
    
    form = ContactForm(request.POST)
    return render(request, "home/contactus.html", {'contact_form':form})


def post_draft_list(request):
    posts = BloodRequest.objects.filter(status = STATUS_DRAFT)
    return render(request, 'home/draft.html', {'posts': posts})

def donor_review(request):
    review = DonorRequest.objects.all()
    return render(request, 'home/review.html', {'review':review})

    
def detailDraft_view(request, name_slug):
    posts = get_object_or_404(BloodRequest, slug=name_slug)
    return render(request, 'home/detail-draft.html', {'posts':posts,})
    
def error_404(request, exception):
        data = {}
        return render(request,'home/404.html', data)

def error_500(request, *args):
        data = {}
        return render(request,'home/500.html', data)
    

def donor_form(request):
    form = DonorForm()
    if request.method == 'POST':
        #print('Printing POST:', request.POST)
        form = DonorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('home:donor_confirm')
    context = {'form':form}
        
    return render(request, 'home/donor.html', context)

def donor_confirm(request):
    return render(request, 'home/donor_confirm.html')

sociio_ichor/ichor/home/templates/home/base.html
<html lang="en">
{% load static %} {% load i18n %}

<head>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-6Y6L0DXG49"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-6Y6L0DXG49');
    </script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'home/base-style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="icon" href="{% static 'home/ichornotext.png' %}" type="image/x-icon"> {% block head %} {% endblock head %}

</head>



<body>
    <div class="navigation-wrap  start-header start-style">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-md navbar-dark">

                        <a class="navbar-brand" href="{% url 'home:land' %}" target="_blank"><img src="{% static 'home/ichor.png' %}" alt="logo"></a>

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto py-4 py-md-0">

                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" href="{% url 'home:land' %}">Home</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" href="{% url 'home:donate' %}">Live Request</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" href="{% url 'blog:blog-list' %}">Blog</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" href="{% url 'home:donor_review' %}">Reviews</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" href="{% url 'team:team' %}">Our Team</a>
                                </li>
                                {% comment %}
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
                                </li> {% endcomment %}

                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                    <a class="nav-link btn-donate   " href="{% url 'home:donor' %}">Register as a donor</a>
                                </li>


                            </ul>

                        </div>

                    </nav>
                </div>
            </div>
        </div>
    </div>



    {% block content %} {% endblock content %}



    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h2 class="footer-text">Get in touch.</h2>

                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Contacts</h6>
                    <ul class="footer-links">
                        <li><a href="tel:8886660800">Phone</a></li>
                        <li><a href="mailto:hr@sociio.org">Mail</a></li>
                        <li><a href="https://www.instagram.com/sociio_ichor/">Instagram</a></li>

                    </ul>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h6>Quick Links</h6>
                    <ul class="footer-links">
                        <li><a href="{% url 'home:about' %}">About Us</a></li>
                        <!-- <li><a href="{% url 'home:land' %}">Home</a></li> -->
                        <li><a href="{%  url 'home:donate' %}">Donate Blood</a></li>
                        <li><a href="{%  url 'home:contact' %}">Contact us</a></li>
                        <li><a href="{% url 'home:donor' %}">Register as donor</a></li>
                        <li><a href="{% url 'newsletter:letter-index' %}">Subscribe to newsletter</a></li>
                        <!-- <li><a href="{% url 'home:privacy' %}">Privacy Policy</a></li> -->
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by
                        <a href="{% url 'home:land' %}">Sociio Ichor</a>.
                        <br>
                        <a href="{% url 'newsletter:unsubscribe' %}">Unsubscribe from mailing list</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    {% block scripts %} {% endblock scripts %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script>
        var jq14 = jQuery.noConflict(true);

        (function($) {
            $(document).ready(function() {
                // your logic
            });
        }(jq14));
    </script>

</html>

sociio_ichor/ichor/home/templates/home/detail-draft.html
{% extends 'home/base.html' %}

{% load static %}
{% load social_share %}
{% block head %}
    <title> Details | Sociio Ichor</title>
    <style>
        .ichor-details{
            margin-top: 15%;
            background-color: white; 
            margin-bottom: 10%;
            border-radius: 4px;
            width: 100%;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        }

        .ichor-details .img{
            width: 120%;
            margin-top: 3%;
        }

        .btn-sm-2{
            width: 30%;
        }
      
        @media only screen and (max-width: 768px){
            .ichor-details{
                width: 90%;
                margin-top: 35%;
            }
            .img img{
                width: 200px !important;
            }
            .btn-sm-2{
                width: 100px;
            }
            .ichor-guide{
                margin-top: 0.5%;
            }
        }
       .ichor-guide{
           margin-top: 5%;
       }
    </style>
{% endblock head %}


{% block content %}
    <div class="container ichor-details ">
    <div class="row">
        <div class="col-lg-3 img text-center">
            <img src="{% static 'home/logox.png' %}" width="80%" style="margin-top: 15%;" alt="logo">

        </div>
        <div class="col-lg-4 my-5">
      <p class="lead">Sorry this request has been closed.</p>
</div>

     


    </div>    
    </div>
    
    {% block script %}

    <script>
        function getURL() {
    alert("Copy : " + window.location.href);
}
    </script>
        
    {% endblock script %}
        

{% endblock content %}
    
    

sociio_ichor/ichor/home/templates/home/donor_confirm.html
{% extends 'home/base.html' %}

{% load static %}
{% block head %}
<title>Thankyou!</title>
    <style>
              @media (max-width: 767px) { 
                  .head-text{
                      margin-top: 36%;
                  }

                  h2{
                      font-size: 1rem;
                  }
              }
              .head-text {
      font-family:Oswald;
      font-size: 4.5rem;
      letter-spacing: 2px;
      font-weight: 700;
  color: #CA4246;
  
  }
    </style>
{% endblock head %}
    


{% block content %}
<div style="margin-top: 15%; height: 50vh;" class="container" >
        <h1 class="head-text">Thank you!
        </h1>
        <h2 class="text-center">We will get in touch with you as soon as we find a match</h2>
    
      
      <!-- <div class="col-lg-6">
          <img src="{% static 'home/9.png' %} " width="100%" height="100%" alt="">
      </div> -->
</div>
{% endblock content %}
    

sociio_ichor/ichor/home/templates/home/draft.html
{% extends 'home/base.html' %}

{% block content %}
   
         
         
    {% for b in posts %}
     
         
         
    <div class="col-lg-4">
       <div class="card card-margin data-aos="fade-up"
       data-aos-anchor-placement="top-bottom"">
           <div class="card-header no-border">
           </div>
           <div class="card-body pt-0">
               <div class="kmc">
                  <p class="lead">This request has been closed, to view open request <a href="#">click here.</a></p>
               </div>
               <div class="kmc-blood-action">
                <a href="{% url 'home:draft' b.slug %}" class=" btn btn-sm btn-border-primary">Details</a>
            </div>
           </div>
       </div>
   </div>


    {% endfor %}
{% endblock %}

sociio_ichor/ichor/home/templates/home/home.html
 {% extends 'home/base.html' %} {% block head %} {% load social_share %}
<title>Sociio Ichor | Donate</title>
{% endblock head %} {% block content %}

<div class="container" style="margin-top: 9%; margin-bottom: 10%;">
    <div class="form-inline text-center container-fluid ">


        <form class="form-inline search-ichor" action="{% url 'home:search-blood' %}" method="get">
            <input class="form-control mr-sm-2" type="text" name="q" id="q" placeholder="Search by blood group" aria-label="Search">
            <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
        </form>



    </div>
    <div class="row" style="margin-top: 5%;">




        {% if blood %} {% for b in blood %}

        <a style="text-decoration: none;" href="{% url 'home:details' b.slug %}">
            <div class="col-lg-4">
                <div class="card card-margin">
                    <div class="card-header no-border">
                    </div>
                    <div class="card-body pt-0">

                        <div class="kmc">
                            <div class="kmc-title-wrapper">

                                <div class="kmc-date-primary">

                                    <span class="kmc-date-day">{{ b.blood_request_id }}</span>

                                </div>

                                <a style="text-decoration: none;" href="{% url 'home:details' b.slug %}">
                                    <div class="kmc-blood-info">
                                        <span class="kmc-pro-title">KMC, Manipal - blood bank</span>
                                        <span class="kmc-blood-time">{{ b.time_stamp}}</span>

                                    </div>
                                </a>



                            </div>
                            <a style="text-decoration: none;" href="{% url 'home:details' b.slug %}">
                                <ol class="kmc-blood-points">





                                    {% if b.blood_group %}

                                    <li class="kmc-blood-item"><span><b>Blood Group - </b>{{ b.blood_group }}</span></li>


                                    {% endif %} {% if b.blood_type %}
                                    <li class="kmc-blood-item"><span><b>Blood Type - </b>{{ b.blood_type }}</span></li>

                                    {% endif %} {% if b.units %}
                                    <li class="kmc-blood-item"><span><b>Units required - </b>{{ b.units }}</span></li>

                                    {% endif %}

                                </ol>
                            </a>
                            <div class="row mx-3">
                                <div class="col-lg-4">
                                    {% if b.urgent %}

                                    <a href="{% url 'home:details' b.slug %}" class="button-blink btn btn-border-primary">Urgent</a> {% endif %}
                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>

        {% endfor %} {% else %}
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <p> We do not have any requests for blood donations right now, kindly check back in a few days or <a style="color: black; font-weight: 800;" href="{% url 'home:donor' %}">register as donor now.</a> </p>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <div class="col-lg-12 promo-text text-center">
        <p style="font-family:Oswald; font-size: 160%;"> There is no substitute for blood, it only comes from generous donors. <a class="link-new" href="{% url 'home:donor' %}">Become a donor</a> and save a life, or two.</p>
    </div>

</div>
{% endblock content %}

sociio_ichor/ichor/home/templates/home/review.html
{% extends 'home/base.html' %}


{% block head %}
    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:300,400);
@import url(https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css);
.snip1533 {
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
  color: #9e9e9e;
  display: inline-block;
  font-family: 'Roboto', Arial, sans-serif;
  font-size: 16px;
  margin: 35px 10px 10px;
  max-width: 310px;
  min-width: 250px;
  position: relative;
  text-align: center;
  width: 100%;
  background-color: #ffffff;
  border-radius: 5px;
  border-top: 5px solid #e00451;
}

.snip1533 *,
.snip1533 *:before {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-transition: all 0.1s ease-out;
  transition: all 0.1s ease-out;
}

.snip1533 figcaption {
  padding: 13% 10% 12%;
}

.snip1533 figcaption:before {
  -webkit-transform: translateX(-50%);
  transform: translateX(-50%);
  background-color: #fff;
  border-radius: 50%;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.25);
  color: #e00451;
  content: "\f10e";
  font-family: 'FontAwesome';
  font-size: 32px;
  font-style: normal;
  left: 50%;
  line-height: 60px;
  position: absolute;
  top: -30px;
  width: 60px;
}

.snip1533 h3 {
  color: #3c3c3c;
  font-size: 18px;
  font-weight: 400;
  line-height: 24px;
  margin: 10px 0 5px;
}

.snip1533 h4 {
  font-weight: 400;
  margin: 0;
  opacity: 0.7;

  font-size: 17px;
}

.snip1533 blockquote {
  font-style: italic;
  font-weight: 300;
  margin: 0 0 20px;
  color:black;
}

.promo-text p{
  text-align:center;
  font-size: 150%;
  margin-bottom: 5%;

}
.link-new{
  text-decoration:none;
  color:#e00451;
}
.link-new:hover{
  text-decoration:none;
  color:gray;
}

.ichor-title{
      font-family:Oswald;
      font-size: 4.5rem;
      letter-spacing: 2px;
      font-weight: 700;
      color: rgb(13, 14, 13) !important;
      text-shadow: 0px 2px 2px rgba(7, 3, 3, 0.4);
      margin-bottom:5%; 
      
  }
  .ichor-title span{
      font-family:Oswald;
      font-size: 4.5rem;
      letter-spacing: 2px;
      font-weight: 700;
  color: #CA4246;
  
  }

@media (max-width:767px){
  .ichor-title{
    margin-top: 30% !important;
    font-size:250%;  }

}
    </style>
{% endblock head %}
    

{% block content %}


<div class="container" style="margin-top: 10%;">
<h1 class="ichor-title"> Hear it from the <span>heroes</span> themselves! </h1>

   <div class="row">
    
    {% for r in review %}
    {% if r.comment %}
        <div class="col-lg-4" style="height:500px">
        <figure class="snip1533 card" style="margin-top: 10%; height:90%; background-color: #f1dfd1;
        background-image: linear-gradient(315deg, #f1dfd1 0%, #f6f0ea 74%);" >

            <figcaption>

              <blockquote >
                <img alt="{{ r.full_name }}" style="width:100px; height:100px; border-radius:50%" src="{{ r.photo.url }}">

                 <p class="text-center"> "{{ r.comment }}" </p> <hr>
              </blockquote>
              <h3>{{ r.full_name }}</h3>
              <h4>{{ r.designation  }}</h4>
            </figcaption>
          </figure>


       </div>

    
    {% else %}
    {% endif %}
    {% endfor %}

   </div>
</div>
  <div class="container">
      <div class="row">
      <div class="col-lg-12 promo-text">
      <p  style="font-family:Oswald;"> There is no substitute for blood, it only comes from generous donors. <a class="link-new" href="{% url 'home:donor' %}">Become a donor</a> and save a life, or two.</p>
      </div>
      </div>
      </div>
{% endblock content %}
    