ichor/blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('blog/', views.BlogList.as_view(), name='blog-list'),
    path('blog/<slug:slug>/', views.detail_view, name='blog-detail')
]

ichor/home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    
    path('sociio/', views.base, name='sociio'),
    path('', views.home, name='home'),
    path('donate/', views.BloodListView.as_view(), name='donate'),
    path('search-blood/', views.BloodSearchView.as_view(), name='search-blood'),
    path('donate/detail/<slug:name_slug>/', views.detail_view , name='details'),
    path('register/individual/', views.donor_form, name='donor'),
    path('register/NGO/', views.bank_form, name='bank-donor'),
    path('blood-donation-guidelines/', views.guidelines, name='guidelines'),
    path('register/', views.preform, name='preform'),
    path('contactus/', views.contactus, name = 'contact'),

]

ichor/ichor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from home import views
from django.conf import settings
from django.conf.urls.static import static
import home
from django.conf.urls import handler404, handler500
from django.views.generic.base import TemplateView

admin.site.site_header = 'Sociio Ichor'
admin.site_site_title = 'Sociio Ichor'
admin.site.index_title = 'Sociio Ichor Administration'

urlpatterns = [
    path('editor/', include ('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('team.urls')),
    path('', include('blog.urls')),
    path('', include('newsletter.urls')),

    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),  #add the robots.txt file

    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
     
handler404 = home.views.error_404
handler500 = home.views.error_500

ichor/home/models.py
from django.db import models
from django.db.models.aggregates import Max
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.db.models.signals import post_delete
from django.dispatch import receiver

STATUS_DRAFT = 0
STATUS_PUBLISH = 1

STATUS = (
    (STATUS_DRAFT, "Draft"),
    (STATUS_PUBLISH, "Publish")
)
def upload_review_photo(instance, filename, *kwargs):
    file_path = 'full_name/{filename}'.format(full_name=str(instance.full_name), filename=filename)
    return file_path


BG_CHOICES = (
    ('A+','A+'),
    ('B+','B+'),
    ('O+','O+'),
    ('AB+', 'AB+'),
    ('A-','A-'),
    ('B-','B-'),
    ('O-','O-'),
    ('AB-', 'AB-'),
    ('Hh', 'Hh'),
)
TYPE=(
    ('Whole Blood', 'Whole Blood'),
    ('Plasma', 'Plasma'),
    ('Platelets', 'Platelets'),
)

class states(models.Model):
    id = models.IntegerField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255, null=False)
    def __str__(self):
        return self.name



class cities(models.Model):
    city_id = models.IntegerField(max_length=11, primary_key=True)
    city_name = models.CharField(max_length=100, null=False, default='')
    city_state = models.CharField(max_length=100, null=False, default='')

    def __str__(self):
        return self.city_name


#STATUS=(
    #('0', 'Draft'),
    #('1', 'Publish')
#)

# Create your models here.
class BloodRequest(models.Model):
    blood_request_id = models.AutoField(primary_key=True)
    time_stamp = models.DateTimeField(auto_now_add=True)
    blood_group = models.CharField(
        max_length=20, choices=BG_CHOICES, default=None, blank=True, null=True
    )
    blood_type = models.CharField(
        max_length=50, choices=TYPE, default=None, blank=True, null=True
    )
    acceptable_blood_group = models.CharField(max_length = 100, blank=True, null=True )
    Phone = models.CharField(max_length=10, default='')
    units = models.CharField(max_length=5)
    note = models.TextField(default='', blank=True, null=True)
    address = models.TextField(default='', blank=True, null=True)
    hospital_initials = models.CharField(default='', blank=False, null=False, max_length=50 )
    status = models.IntegerField(choices=STATUS, default=0)
    urgent = models.BooleanField( blank=True, default=False)
    slug = models.SlugField(max_length=400, unique=True, default=None)
    custom_field_key = models.CharField(default='', blank=True, max_length=255)
    custom_field_value = models.CharField(default='', blank=True, max_length=255)

    class Meta:
        verbose_name = 'Blood Request'
    
    
def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.name)
  
pre_save.connect(pre_save_blog_post_receiver, sender=BloodRequest)


class DonorRequest(models.Model):
    full_name = models.CharField(max_length=200, default='')
    date_of_birth = models.DateField(default=None, blank=False)
    email_id = models.EmailField(max_length=200)
    phone = models.CharField(max_length=11, default='')
    city = models.ForeignKey(cities, null=False, max_length=255, on_delete=models.CASCADE )
    state = models.ForeignKey(states, null=False, max_length=255, on_delete=models.CASCADE)

    pin_code = models.IntegerField(default=False)
    # weight = models.CharField(max_length=10, default='')
    I_agree_to_the_terms_and_conditions_stated_below = models.BooleanField(blank=False,  default=True)
    blood_group = models.CharField(
        max_length=4, choices=BG_CHOICES, default=None
    
    )    
    comment = models.TextField(default='', null=True, blank=True)
    designation = models.TextField(default='', null=True, blank=True)
    photo = models.ImageField(upload_to=upload_review_photo, blank=True, default=None, null=True)


class BankRequest(models.Model):
    bloodbank_name = models.CharField(max_length=200, default='')
  
    city = models.ForeignKey(cities, null=False, max_length=255, on_delete=models.CASCADE )
    state = models.ForeignKey(states, null=False, max_length=255, on_delete=models.CASCADE)
    pin_code = models.IntegerField(default=False)
    contact_person = models.CharField(max_length=255, blank=False)
    designation = models.CharField(max_length=255, blank=False)
    email_id = models.EmailField(max_length=200)
    phone = models.CharField(max_length=11, default='')
    # weight = models.CharField(max_length=10, default='')
    I_agree_to_the_terms_and_conditions_stated_below = models.BooleanField(blank=False,  default=True)
   

ichor/home/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import ModelForm
from home.models import DonorRequest, BankRequest
from django.forms.fields import DateField
from django.contrib.admin.widgets import AdminDateWidget
# from localflavor.in.forms import INStateSelect




class ContactForm(forms.Form):
    name = forms.CharField(max_length = 150)
    company =forms.CharField(max_length=200)
    email_address = forms.EmailField(max_length = 150)
    phone = forms.CharField(max_length=10)
    message = forms.CharField(widget = forms.Textarea, max_length = 2000)

        
         
class DonorForm(forms.ModelForm):
    
    class Meta:
        model = DonorRequest
        fields = ['full_name', 'email_id', 'date_of_birth', 'phone','state', 'city', 'pin_code', 'blood_group','I_agree_to_the_terms_and_conditions_stated_below']
        widgets = {
            'full_name': forms.TextInput(attrs = {'class':'form-control'}),
            #'city': INStateSelect(attrs=None),
            #'state': forms.TextInput(attrs = {'class':'form-control'}),
            'pin_code': forms.NumberInput(attrs = {'class':'form-control'}),
            'phone': forms.TextInput(attrs = {'class':'form-control'}),
            'date_of_birth':forms.DateInput(format = '%Y-%m-%d', attrs={'type': 'date'}),
            'email_id': forms.EmailInput(attrs = {'class':'form-control'}),
            #'weight': forms.NumberInput(attrs = {'class':'form-control', 'placeholder':'Body weight'}),
        }
        
         
class BankForm(forms.ModelForm):
    
    class Meta:
        model = BankRequest
        fields = '__all__'
        widgets = {
            'bloodbank_name': forms.TextInput(attrs = {'class':'form-control'}),
            #'city': INStateSelect(attrs=None),
            #'state': forms.TextInput(attrs = {'class':'form-control'}),
            'pin_code': forms.NumberInput(attrs = {'class':'form-control'}),
            'phone': forms.TextInput(attrs = {'class':'form-control'}),
            'email_id': forms.EmailInput(attrs = {'class':'form-control'}),
            #'weight': forms.NumberInput(attrs = {'class':'form-control', 'placeholder':'Body weight'}),
        }
        
        
        
    
class ContactForm(forms.Form):
    name = forms.CharField(max_length = 150)
    company =forms.CharField(max_length=200)
    email_address = forms.EmailField(max_length = 150)
    phone = forms.CharField(max_length=10)
    message = forms.CharField(widget = forms.Textarea, max_length = 2000)

        

ichor/home/views.py
from re import template
import re
from django.db.models import query
from django.db.models.query import RawQuerySet
from django.shortcuts import render, redirect
from .models import BloodRequest, DonorRequest, STATUS_DRAFT
from django.views.generic import ListView, DetailView
from django.views import generic
from django.shortcuts import render,get_object_or_404
from .forms import ContactForm, BankForm
from django.template import RequestContext


from django.core.mail import send_mail, BadHeaderError
from .models import STATUS_PUBLISH, STATUS_DRAFT
from home.forms import DonorForm
from django.db.models import Q
from django.http import HttpResponse

# Create your views here.
def base(request):
    return render(request, 'home/base.html')


    
def guidelines(request):
    return render(request, 'home/guidelines.html')


def home(request):
    return render(request, 'home/home.html')
def preform(request):
    return render(request, 'home/preform.html')

def error_404(request, exception):
        data = {}
        return render(request,'home/404.html', data)

def error_500(request, *args):
        data = {}
        return render(request,'home/500.html', data)


class BloodListView(ListView):
    model=BloodRequest
    template_name = 'home/request.html'
    queryset=BloodRequest.objects.filter(status=STATUS_PUBLISH).order_by('-time_stamp')
    context_object_name='blood'
     

class BloodSearchView(ListView):
    model=BloodRequest
    template_name='home/request.html'
    context_object_name='blood'
    
    def get_queryset(self):
        query=self.request.GET.get('q')
        return BloodRequest.objects.filter(blood_group__icontains=query, status=STATUS_PUBLISH)
    

class BloodDetailView(DetailView):
    model = BloodRequest
    template_name = 'home/request.html'
    
    
def detail_view(request, name_slug):
    blood = get_object_or_404(BloodRequest.objects.filter(status=STATUS_PUBLISH), slug=name_slug)
    return render(request, 'home/detail.html', {'blood':blood,})


def donor_form(request):
    form = DonorForm()
    if request.method == 'POST':
        #print('Printing POST:', request.POST)
        form = DonorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('home:donor_confirm')
    context = {'form':form}
        
    return render(request, 'home/donor.html', context)

def bank_form(request):
    bank_form = BankForm()
    if request.method == 'POST':
        #print('Printing POST:', request.POST)
        bank_form = BankForm(request.POST)
        if bank_form.is_valid():
            bank_form.save()
            return redirect ('home:bank_confirm')
    context = {'bank_form':bank_form}
        
    return render(request, 'home/bank_donor.html', context)


def contactus(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Subject Inquiry"
            body = {
                'name': form.cleaned_data['name'], 
			    'company': form.cleaned_data['company'], 
			    'email': form.cleaned_data['email_address'], 
			    'message':form.cleaned_data['message'], 
			    'phone':form.cleaned_data['phone'], 
       
                }
            message = "\n".join(body.values())
            recepient = str(form['email_address'].value())

            try:
                send_mail(subject, message, recepient, ['sociio.organisation@gmail.com']) 
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect ("home:donate")
    
    form = ContactForm(request.POST)
    return render(request, "home/contactus.html", {'contact_form':form})

ichor/home/templates/home/base.html
{% load static %}{% load i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Software 2.0 </title>
  <link rel="shortcut icon" href="image/favicon.png" type="image/x-icon">
  <!-- Bootstrap , fonts & icons  -->
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'home/fonts/icon-font/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'home/fonts/typography-font/typo.css' %}">
  <link rel="stylesheet" href="{% static 'home/fonts/fontawesome-5/css/all.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Gothic+A1:wght@400;500;700;900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&display=swap" rel="stylesheet">
  <!-- Plugin'stylesheets  -->
  <link rel="stylesheet" href="{% static 'home/plugins/aos/aos.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/plugins/slick/slick.min.css' %}">
  <!-- Vendor stylesheets  -->
  <link rel="stylesheet" href="{% static 'home/css/main.css' %}">
  <!-- Custom stylesheet -->

  {% block head %}
  
  {% endblock head %}
</head>

<body data-theme-mode-panel-active data-theme="light" style="font-family: 'Mazzard H';">
  <div class="site-wrapper overflow-hidden position-relative">
    <!-- Site Header -->
    <!-- Preloader -->
    <!-- <div id="loading">
    <div class="preloader">
     <img src="./image/preloader.gif" alt="preloader">
   </div>
   </div>    -->
    <!--Site Header Area -->
    <header class="site-header site-header--menu-left landing-11-menu site-header--absolute site-header--sticky" style="box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px;">
      <div class="container">
        <nav class="navbar site-navbar">
          <!-- Brand Logo-->
          <div class="brand-logo">
            <a href="{% url 'home:home' %}">
              <!-- light version logo (logo must be black)-->
              <img src="{% static 'home/image/logo/ichor.png' %}" width='80px' alt="Sociio Ichor" class="light-version-logo">
              <!-- Dark version logo (logo must be White)-->
              <img src="{% static 'home/image/logo/ichor.png' %}" alt="Sociio Ichor" class="dark-version-logo">
            </a>
          </div>
          <div class="menu-block-wrapper">
            <div class="menu-overlay"></div>
            <nav class="menu-block" id="append-menu-header">
              <div class="mobile-menu-head">
                <div class="go-back">
                  <i class="fa fa-angle-left"></i>
                </div>
                <div class="current-menu-title"></div>
                <div class="mobile-menu-close">&times;</div>
              </div>
              <ul class="site-menu-main">
               
                <li class="nav-item">
                  <a href="{% url 'home:donate' %}" class="nav-link-item">Live Request <sup>BETA</sup> </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'home:home' %}" class="nav-link-item">Home</a>
                </li>
                 <li class="nav-item nav-item-has-children">
                  <a href="#" class="nav-link-item drop-trigger">Know More<i class="fas fa-angle-down"></i>
                  </a>
                  <ul class="sub-menu" id="submenu-9">
                    <li class="sub-menu--item">
                      <a href="{% url 'home:contact' %}">Contact Us</a>
                    </li>
                    <li class="sub-menu--item">
                      <a href="{% url 'blog:blog-list' %}">Blog</a>
                    </li>
                    <li class="sub-menu--item">
                      <a href="{% url 'home:guidelines' %}">Am I Eligible To Donate?</a>
                    </li>
                
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
          <div class="header-btns  header-btn-l11 ms-auto d-none d-xs-inline-flex align-items-center">
            <!-- <a class="btn log-in-btn focus-reset" href="#">
              Log in
            </a> -->
            <a class="request-btn download-trail-btn btn focus-reset" href="{% url 'home:preform' %}">
              Register as donor
            </a>
          </div>
          <!-- mobile menu trigger -->
          <div class="mobile-menu-trigger">
            <span></span>
          </div>
          <!--/.Mobile Menu Hamburger Ends-->
        </nav>
      </div>
    </header>


        {% block content %} {% endblock content %}

    <!-- Footer Area -->
    <footer class="footer-l-11 text-center text-md-start">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="footer-logo-l-11">
              <a href="#">              
              <img src="{% static 'home/image/logo/ichor.png' %}" width='80px' alt="" class="light-version-logo">
              </a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="footer-widget-l-11">
              <ul class="pl-0 list-unstyled d-flex flex-wrap justify-content-center align-items-end ">
                <li class="d-flex"><a href="">About</a></li>
                <li class="d-flex"><a href="">Features</a></li>
                <li class="d-flex"><a href="">Works</a></li>
                <li class="d-flex"><a href="">Career</a></li>
                <li class="d-flex"><a href="">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="social-icons-l-11">
              <ul class="pl-0 list-unstyled d-flex  justify-content-center justify-content-md-end align-items-end ">
                <li class="d-flex flex-column justify-content-center"><a href="#"><i
                                    class="fab fa-twitter"></i></a></li>
                <li class="d-flex flex-column justify-content-center"><a href="#"><i
                                    class="fab fa-facebook-f"></i></a></li>
                <li class="d-flex flex-column justify-content-center"><a href="#"><i
                                    class="fab fa-google"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <div class="copyright-area-l-11">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="text-center">
              <p>© Grayic 2021 All right reserved. </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js" crossorigin="anonymous"></script>
  <!-- Vendor Scripts -->
  <script src="{% static 'home/js/vendor.min.js'%} "></script>
  <!-- Plugin's Scripts -->
  <script src="{% static 'home/plugins/aos/aos.min.js' %}"></script>
  <script src="{% static 'home/plugins/slick/slick.min.js' %}"></script>
  <script src="{% static 'home/plugins/menu/menu.js' %}"></script>
  <!-- Activation Script -->
  <script src="{% static 'home/js/custom.js' %}"></script>
<script src="{% static 'home/ichor.js' %}"></script>
</body>
</html>

ichor/home/templates/home/guidelines.html
{% extends "home/base.html" %}

{% block content %}
<div class="container" style="margin-top: 10%; font-family: Karla;">
    <h1 class="text-center my-4">Eligibility For Donating Blood</h1>
    <p class="lead" style=" font-size:18px; font-family: Rubik; font-weight: 400; color: black;">
        <span> If you are eligible, you may register as a blood donor, but at the time of donating blood, follow the instructions mentioned below:</span>
        <br>
        <li>         Your weight should be 45kg or above
        </li>
         <br>
  
        <li> Pulse rate should be between 50 and 100 per minute, without any irregularities.</li>
         <br>
        <li> Blood pressure should be diastolic 50 to 100 mm Hg and Systolic 100 to 180 mm Hg.</li>
         <br>
         <li>Body temperature should be normal and oral temperature should not exceed 37.5 degree Celsius.</li>
         <br>
        <li> Should not have undergone any treatment for rabies or received Hepatitis B immune globulin within the past one year.</li>
         <br>
         <li>Should not have donated blood within the last three months.</li>
         <br>
        <li> Should not have been treated for malaria within the last three months.</li>
         <br>
         
         <li>Should not have undergone any immunization within the past one month.</li>
         <br>
        <li> Should not have undergone any dental work or taken aspirin within the last 72 hours.</li>
         <br>
        <li> Should not have consumed alcohol within the last 9 hours.</li>
         <br>
         <i>                          If you have any chronic disease that is not mentioned here, you may register, but please inform the patient or the doctor or the hospital staff before you donate blood.
         </i>  <br><br><br>                       
         <b>                           Please do not register as a blood donor or donate blood in case
         </b><br>
         You are HIV+.
         <br>
         You are suffering, or have a history of cancer.
         <br>
         You are suffering from any blood clotting disorder, such as haemophilia.
         
                               </div>
</div>
{% endblock content %}

ichor/home/templates/home/preform.html
{% extends "home/base.html" %}

{% block content %}
<div class="container text-center preform-div"  data-aos="fade" data-aos-delay="300" data-aos-duration="1000" style="margin-top:15%;">
    <div class="card ">
        <div class="card-body kmc-card">
            <h1 class="my-5" >How do you want to register?</h1>
         <div class="group my-5">
            <a href="{% url 'home:donor' %}" > <button class="btn preform mx-3">Individual</button></a>

            <a href="{% url 'home:bank-donor' %}" > <button class="btn preform mx-3">NGO</button></a>
         </div>

        </div>
    </div>
</div>
{% endblock content %}

ichor/home/templates/home/request.html
 {% extends 'home/base.html' %} {% block head %} 
<title>Sociio Ichor | Donate</title>
<style>
    body{
        background-color: rgb(255, 255, 255);
    }
</style>
{% endblock head %} {% block content %}



<div class="container search-bar" style="margin-top:8%; margin-bottom: 10%;">
   <div class="col-lg-4">
    <form  action="{% url 'home:search-blood' %}" method="get">
        <div class="input-group mb-4">
          <input  type="text" name="q" id="q" placeholder="Search by blood group" aria-label="Search" class="form-control">
          <div class="input-group-append">
            <button id="button-addon5" type="submit" class="btn-search btn btn-primary"><i class="fa fa-search"></i></button>
          </div>
        </div>
      </form>
   </div>
    <div class="row" style="margin-top: 5%;">
        {% if blood %} 
        
        {% for b in blood %}
        <div class="col-lg-4" data-aos="fade-up" data-aos-delay="300" data-aos-duration="700">
        <a class="full-link" href="{% url 'home:details' b.slug %}" style="text-decoration: none;">
            <div class="card kmc-card my-2">
                <div class="header card-body">
                    <span style="font-size: 60px;">{{ b.blood_request_id }}</span>  
                     <span style="font-size: 20px;">KMC, Manipal - Blood Bank</span>
                    <br>
                    <div class="kmc-blood-info">
                     <span class="kmc-blood-time">{{ b.time_stamp}}</span>
                    </div>
                    <ol class="kmc-blood-points">

                        {% if b.blood_group %}

                        <li class="kmc-blood-item"><span><b>Blood Group - </b>{{ b.blood_group }}</span></li>


                        {% endif %} {% if b.blood_type %}
                        <li class="kmc-blood-item"><span><b>Blood Type - </b>{{ b.blood_type }}</span></li>

                        {% endif %} {% if b.units %}
                        <li class="kmc-blood-item"><span><b>Units required - </b>{{ b.units }}</span></li>

                        {% endif %}

                    </ol>
                    <a  href="{% url 'home:details' b.slug %}">                    
                        <button class="btn btn-dark">Donate Now</button> </a>                    {% if b.urgent %}
                        <a  href="{% url 'home:details' b.slug %}">                    

                      <button class="btn button-red">Urgent</button></a>

                    {% else %}
                    {% endif %}
                </div>
            </div>
        </a>
        </div>
        {% endfor %} {% else %}
        <div class="container">
            <div class="card kmc-card">
                <div class="card-body">
                    <p> We do not have any requests for blood donations right now <a style="color: black; font-weight: 800;" href="{% url 'home:donor' %}">register as donor now.</a> </p>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <div class="col-lg-12 promo-text text-center my-5 " data-aos="fade" data-aos-delay="1000" data-aos-duration="1000">
        <p style="font-family:Rubik; font-size: 120%;"> There is no substitute for blood, it only comes from generous donors. <a class="link-new" href="{% url 'home:donor' %}">Become a donor</a> and save a life, or two.</p>
    </div>

</div>
{% endblock content %}